spring:
  application:
    name: infuq-excel-consumer
  redis:
    host: 192.168.31.129
    port: 6379
    database: 2
    password: 9527
  datasource:
    url: jdbc:mysql://192.168.31.129:3306/db0?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 9527
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maxPoolSize: 10
      minIdle: 5

mq:
  name-server: 192.168.31.129:8876
  access-key: ...
  secret-key: ...
  consumer:
    id: GID_EXCEL_CONSUMER_TOOLS
    topic: TEST
    tags:
      - upload
      - export
    consumeMessageBatchMaxSize: 3
    consumeThreadMin: 20
    consumeThreadMax: 64

server:
  port: 59081
  tomcat:
    basedir: /Users/infuq/logs/tmp
    max-threads: 100
    min-spare-threads: 20
    accept-count: 100

